spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/jstack_system_acronym
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/000-master.xml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false

management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus